<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ApiError, apiRequest } from '../auth'
import type { CardTemplate } from '../card'
import AppShell from '../components/AppShell.vue'
import CardPreview from '../components/CardPreview.vue'

const saving = ref(false); const loading = ref(true); const message = ref(''); const errorMessage = ref('')
const modules = [{ code: 'profile', name: '个人信息' }, { code: 'contact', name: '联系方式' }, { code: 'social', name: '社交账号' }, { code: 'bio', name: '个人简介' }]
const lockOptions = [{ code: 'theme_color', name: '主题色' }, { code: 'logo_url', name: 'Logo' }, { code: 'module_order', name: '模块顺序' }]
const editableOptions = [{ code: 'display_name', name: '姓名' }, { code: 'headline', name: '职位/标语' }, { code: 'avatar_url', name: '头像' }, { code: 'bio', name: '简介' }, { code: 'phone', name: '电话' }, { code: 'email', name: '邮箱' }, { code: 'wechat', name: '微信' }, { code: 'website', name: '网站' }, { code: 'socials', name: '社交账号' }, { code: 'theme_color', name: '个性主题色' }, { code: 'logo_url', name: '个性 Logo' }, { code: 'module_order', name: '个性模块顺序' }]
const form = reactive({ name: '', theme_color: '#1c6a42', logo_url: '', module_order: [] as string[], locked_fields: [] as string[], employee_editable_fields: [] as string[] })
const sample = computed<Record<string, unknown>>(() => ({ company_name: '示例企业', display_name: '数字名片', headline: '让每一次连接更有价值', phone: '138 0000 0000', email: 'hello@example.com', bio: '这是企业名片模板的实时预览。', socials: [{ platform: 'LinkedIn', url: 'linkedin.com/in/example' }], ...form, logo_url: form.logo_url || null }))
async function load() { try { const value = await apiRequest<CardTemplate>('/tenant/card-template'); Object.assign(form, { name: value.name, theme_color: value.theme_color, logo_url: value.logo_url ?? '', module_order: [...value.module_order], locked_fields: [...value.locked_fields], employee_editable_fields: [...value.employee_editable_fields] }) } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '模板加载失败' } finally { loading.value = false } }
function move(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= form.module_order.length) return; const values = [...form.module_order]; [values[index], values[target]] = [values[target], values[index]]; form.module_order = values }
async function save() { saving.value = true; message.value = ''; errorMessage.value = ''; try { await apiRequest('/tenant/card-template', { method: 'PUT', body: JSON.stringify({ name: form.name, theme_color: form.theme_color, logo_url: form.logo_url || null, module_order: [...form.module_order], locked_fields: [...form.locked_fields], employee_editable_fields: [...form.employee_editable_fields] }) }); message.value = '企业名片模板已保存'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '模板保存失败' } finally { saving.value = false } }
onMounted(load)
</script>

<template><AppShell><header class="page-header compact"><div><p class="eyebrow">CARD TEMPLATE</p><h1>企业名片模板</h1><p>统一品牌视觉、展示顺序和员工可个性化范围。</p></div></header><div v-if="message" class="notice success">{{ message }}</div><div v-if="errorMessage" class="notice error">{{ errorMessage }}</div><div v-if="loading" class="panel empty-state">正在加载模板…</div><div v-else class="card-editor-layout"><form class="panel form-panel template-form" @submit.prevent="save"><label><span>模板名称</span><input v-model.trim="form.name" required /></label><label><span>企业主题色</span><div class="color-field"><input v-model="form.theme_color" type="color" /><input v-model.trim="form.theme_color" pattern="#[0-9a-fA-F]{6}" required /></div></label><label><span>Logo 地址</span><input v-model.trim="form.logo_url" type="url" /></label><fieldset><legend>模块顺序</legend><div v-for="(code, index) in form.module_order" :key="code" class="order-row"><b>{{ modules.find(item => item.code === code)?.name }}</b><button type="button" class="link-button" @click="move(index, -1)">上移</button><button type="button" class="link-button" @click="move(index, 1)">下移</button></div></fieldset><fieldset class="check-grid"><legend>锁定品牌字段</legend><label v-for="field in lockOptions" :key="field.code"><input v-model="form.locked_fields" type="checkbox" :value="field.code" />{{ field.name }}</label></fieldset><fieldset class="check-grid"><legend>员工允许编辑</legend><label v-for="field in editableOptions" :key="field.code"><input v-model="form.employee_editable_fields" type="checkbox" :value="field.code" />{{ field.name }}</label></fieldset><button class="primary-button" :disabled="saving">{{ saving ? '正在保存…' : '保存模板' }}</button></form><aside class="preview-panel"><p class="eyebrow">LIVE PREVIEW</p><CardPreview :data="sample" device="mobile" /></aside></div></AppShell></template>
