<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ApiError, apiRequest } from '../auth'
import type { Material } from '../product'
import AppShell from '../components/AppShell.vue'

const materials = ref<Material[]>([]); const loading = ref(true); const uploading = ref(false); const errorMessage = ref(''); const message = ref(''); const access = ref<'public' | 'private'>('private')
const apiBase = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000/api/v1'
const previewUrl = (material: Material) => material.access === 'public' ? `${apiBase}/public/materials/${material.id}` : ''
const grouped = computed(() => ({ image: materials.value.filter(item => item.kind === 'image'), video: materials.value.filter(item => item.kind === 'video'), pdf: materials.value.filter(item => item.kind === 'pdf') }))
async function load() { loading.value = true; try { materials.value = await apiRequest<Material[]>('/tenant/materials') } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '素材加载失败' } finally { loading.value = false } }
async function upload(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; uploading.value = true; errorMessage.value = ''; try { await apiRequest('/tenant/materials?' + new URLSearchParams({ name: file.name, access: access.value }), { method: 'POST', headers: { 'Content-Type': file.type }, body: file }); message.value = '素材上传成功'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? `${error.message}，可重新选择文件重试` : '上传失败，可重新选择文件重试' } finally { uploading.value = false; input.value = '' } }
async function toggleAccess(material: Material) { try { await apiRequest(`/tenant/materials/${material.id}/access`, { method: 'PATCH', body: JSON.stringify({ access: material.access === 'public' ? 'private' : 'public' }) }); await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '访问范围更新失败' } }
async function remove(material: Material) { if (!window.confirm(`确认删除素材“${material.name}”？`)) return; try { await apiRequest(`/tenant/materials/${material.id}`, { method: 'DELETE' }); message.value = '素材已删除'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '素材删除失败' } }
const formatSize = (size: number) => size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`
onMounted(load)
</script>

<template><AppShell><header class="page-header compact"><div><p class="eyebrow">MATERIAL LIBRARY</p><h1>企业素材库</h1><p>统一管理产品图片、视频和 PDF 销售资料。</p></div><div class="header-actions"><select v-model="access"><option value="private">上传为私有</option><option value="public">上传为公开</option></select><label class="primary-button file-button">{{ uploading ? '正在上传…' : '上传素材' }}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,application/pdf" :disabled="uploading" @change="upload" /></label></div></header><div v-if="message" class="notice success">{{ message }}</div><div v-if="errorMessage" class="notice error">{{ errorMessage }}</div><div v-if="loading" class="panel empty-state">正在加载素材…</div><template v-else><section v-for="kind in ['image', 'video', 'pdf'] as const" :key="kind" class="material-section"><h2>{{ kind === 'image' ? '图片' : kind === 'video' ? '视频' : 'PDF 文件' }} <small>{{ grouped[kind].length }}</small></h2><div v-if="grouped[kind].length" class="material-grid"><article v-for="material in grouped[kind]" :key="material.id" class="material-card"><div class="material-thumb"><img v-if="material.kind === 'image' && previewUrl(material)" :src="previewUrl(material)" alt="" /><span v-else>{{ material.kind === 'image' ? 'PRIVATE IMAGE' : material.kind === 'video' ? 'VIDEO' : 'PDF' }}</span></div><b>{{ material.name }}</b><small>{{ formatSize(material.size_bytes) }} · {{ material.access === 'public' ? '公开' : '私有' }}</small><div><button class="link-button" @click="toggleAccess(material)">{{ material.access === 'public' ? '设为私有' : '设为公开' }}</button><button class="link-button danger" @click="remove(material)">删除</button></div></article></div><div v-else class="panel empty-state">暂无{{ kind === 'image' ? '图片' : kind === 'video' ? '视频' : 'PDF' }}素材</div></section></template></AppShell></template>
