<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ApiError, apiRequest } from '../auth'
import type { OpenApplication, WebhookDelivery } from '../openPlatform'
import AppShell from '../components/AppShell.vue'

const apps = ref<OpenApplication[]>([]); const deliveries = ref<WebhookDelivery[]>([]); const selected = ref(''); const credential = ref(''); const signingSecret = ref(''); const error = ref(''); const message = ref('')
const appForm = reactive({ name: '', scopes: ['leads.write'] as string[], rate_limit_per_minute: 60 }); const webhook = reactive({ target_url: '', events: ['lead.created'] as string[] })
async function load() { try { [apps.value, deliveries.value] = await Promise.all([apiRequest<OpenApplication[]>('/tenant/open/apps'), apiRequest<WebhookDelivery[]>('/tenant/open/deliveries')]) } catch (e) { error.value = e instanceof ApiError ? e.message : '开放平台数据加载失败' } }
async function createApp() { try { const result = await apiRequest<OpenApplication & { app_secret: string; warning: string }>('/tenant/open/apps', { method: 'POST', body: JSON.stringify(appForm) }); credential.value = `App Key: ${result.app_key}\nApp Secret: ${result.app_secret}\n${result.warning}`; selected.value = result.id; await load() } catch (e) { error.value = e instanceof ApiError ? e.message : '应用创建失败' } }
async function rotate(item: OpenApplication) { if (!window.confirm('轮换后旧密钥立即失效，是否继续？')) return; const result = await apiRequest<OpenApplication & { app_secret: string; warning: string }>(`/tenant/open/apps/${item.id}/rotate`, { method: 'POST' }); credential.value = `App Key: ${result.app_key}\nApp Secret: ${result.app_secret}\n${result.warning}` }
async function toggle(item: OpenApplication) { await apiRequest(`/tenant/open/apps/${item.id}/status`, { method: 'PATCH', body: JSON.stringify({ is_active: !item.is_active }) }); await load() }
async function createWebhook() { if (!selected.value) return; try { const result = await apiRequest<{ signing_secret: string; warning: string }>(`/tenant/open/apps/${selected.value}/webhooks`, { method: 'POST', body: JSON.stringify(webhook) }); signingSecret.value = `${result.signing_secret}\n${result.warning}`; message.value = 'Webhook 订阅已创建' } catch (e) { error.value = e instanceof ApiError ? e.message : 'Webhook 创建失败' } }
async function retry(item: WebhookDelivery) { await apiRequest(`/tenant/open/deliveries/${item.id}/retry`, { method: 'POST' }); await load() }
onMounted(load)
</script>

<template><AppShell><header class="page-header compact"><div><p class="eyebrow">OPEN PLATFORM · API V1</p><h1>消息中心与开放平台</h1><p>管理应用凭据、最小权限作用域、调用频率和 Webhook 投递。</p></div></header><div v-if="message" class="notice success">{{ message }}</div><div v-if="error" class="notice error">{{ error }}</div><section class="settings-grid"><form class="panel form-stack" @submit.prevent="createApp"><h2>创建开放应用</h2><label><span>应用名称</span><input v-model.trim="appForm.name" required /></label><fieldset><legend>权限范围</legend><label class="checkbox-row"><input v-model="appForm.scopes" value="leads.write" type="checkbox" />创建线索</label><label class="checkbox-row"><input v-model="appForm.scopes" value="customers.read" type="checkbox" />读取客户</label><label class="checkbox-row"><input v-model="appForm.scopes" value="customers.write" type="checkbox" />更新客户</label></fieldset><label><span>每分钟调用上限</span><input v-model.number="appForm.rate_limit_per_minute" type="number" min="1" /></label><button class="primary-button">创建并生成凭据</button><pre v-if="credential" class="notice error">{{ credential }}</pre></form><form class="panel form-stack" @submit.prevent="createWebhook"><h2>Webhook 订阅</h2><label><span>应用</span><select v-model="selected" required><option value="">请选择</option><option v-for="item in apps" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>HTTPS 回调地址</span><input v-model.trim="webhook.target_url" type="url" required /></label><fieldset><legend>事件</legend><label class="checkbox-row"><input v-model="webhook.events" value="lead.created" type="checkbox" />线索创建</label><label class="checkbox-row"><input v-model="webhook.events" value="customer.updated" type="checkbox" />客户更新</label></fieldset><button class="primary-button">创建订阅</button><pre v-if="signingSecret" class="notice error">{{ signingSecret }}</pre></form></section><section class="panel table-panel"><h2>开放应用</h2><table><thead><tr><th>应用</th><th>App Key</th><th>作用域</th><th>限流</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in apps" :key="item.id"><td>{{ item.name }}</td><td>{{ item.app_key }}</td><td>{{ item.scopes.join('、') }}</td><td>{{ item.rate_limit_per_minute }}/分钟</td><td>{{ item.is_active ? '启用' : '停用' }}</td><td class="actions"><button class="link-button" @click="rotate(item)">轮换密钥</button><button class="link-button danger" @click="toggle(item)">{{ item.is_active ? '停用' : '启用' }}</button></td></tr></tbody></table></section><section class="panel table-panel"><h2>Webhook 投递与失败</h2><table><thead><tr><th>事件</th><th>幂等键</th><th>状态</th><th>尝试</th><th>失败原因</th><th>操作</th></tr></thead><tbody><tr v-for="item in deliveries" :key="item.id"><td>{{ item.event_type }}</td><td>{{ item.idempotency_key }}</td><td>{{ item.status }}</td><td>{{ item.attempts }}/5</td><td>{{ item.error_message || '—' }}</td><td><button v-if="item.status !== 'delivered'" class="link-button" @click="retry(item)">立即重试</button></td></tr></tbody></table></section></AppShell></template>
