<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

interface PublicCard { card_id: string; employee_id: string; data: Record<string, unknown>; published_at: string; share_url: string }
interface ProductSummary { id: string; name: string; summary: string | null; cover_url: string | null }
interface ProductDetail extends ProductSummary { description: string | null; specifications: Record<string, string>; gallery_urls: string[]; video_url: string | null; attachment_urls: string[] }
interface CampaignField { key: string; label: string; type: string; required: boolean; options: string[] }
interface PublicCampaign { id: string; name: string; description: string | null; state: string; remaining: number | null; fields: CampaignField[]; privacy_notice: string; success_message: string }
interface AiAnswer { interaction_id: string; answer: string; uncertain: boolean; citations: Array<{ source_id: string; title: string; excerpt: string }>; handoff_url: string | null; suggestion_notice: string }
const apiBase = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000/api/v1'
const card = ref<PublicCard | null>(null); const loading = ref(true); const unavailable = ref(''); const showQr = ref(false); const toast = ref('')
const products = ref<ProductSummary[]>([]); const selectedProduct = ref<ProductDetail | null>(null)
const showInquiry = ref(false); const submittingInquiry = ref(false); const inquiryMessage = ref(''); const inquiryError = ref('')
const inquiry = ref({ name: '', contact: '', demand: '', privacy_agreed: false, product_id: null as string | null })
const cardId = window.location.pathname.match(/^\/card\/([^/]+)\/?$/)?.[1] ?? ''
const campaignSlug = window.location.pathname.match(/^\/campaign\/([^/]+)\/?$/)?.[1] ?? ''
const aiCompanyCode = window.location.pathname.match(/^\/ai\/([^/]+)\/?$/)?.[1] ?? ''
const aiQuestion = ref(''); const aiAnswer = ref<AiAnswer | null>(null); const aiError = ref(''); const aiLoading = ref(false)
const marketing = ref<PublicCampaign | null>(null); const marketingValues = ref<Record<string, string>>({}); const marketingConsent = ref(false); const marketingMessage = ref(''); const marketingError = ref(''); const marketingSubmitting = ref(false)
const source = (new URLSearchParams(window.location.search).get('source') ?? 'direct').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 64) || 'direct'
const data = computed(() => card.value?.data ?? {}); const modules = computed(() => (data.value.module_order as string[] | undefined) ?? ['profile', 'contact', 'social', 'bio']); const socials = computed(() => (data.value.socials as Array<{ platform: string; url: string }> | undefined) ?? [])
const value = (key: string) => String(data.value[key] ?? '')
const assetUrl = (path: string | null) => !path ? '' : /^https?:\/\//.test(path) ? path : `${new URL(apiBase).origin}${path}`
function visitorId() { const key = 'digitalcard_visitor_id'; let id = localStorage.getItem(key); if (!id) { id = crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; localStorage.setItem(key, id) } return id }
async function track(event_type: string, product_id: string | null = null) { if (!card.value) return; try { await fetch(`${apiBase}/public/cards/${card.value.card_id}/events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ event_type, visitor_id: visitorId(), source, product_id }), keepalive: true }) } catch { /* Analytics must never block customer actions. */ } }
function linkFor(channel: string) { if (!card.value) return ''; const url = new URL(card.value.share_url); url.searchParams.set('source', channel); return url.toString() }
async function copyText(text: string, message: string) { await navigator.clipboard.writeText(text); toast.value = message; window.setTimeout(() => { toast.value = '' }, 1800) }
async function copyShare() { await copyText(linkFor('copy'), '分享链接已复制'); void track('share_copy') }
async function nativeShare() { const link = linkFor('native'); if (navigator.share) { await navigator.share({ title: value('display_name'), text: value('headline'), url: link }) } else await copyText(link, '分享链接已复制'); void track('share_copy') }
async function copyWechat() { await copyText(value('wechat'), '微信号已复制'); void track('wechat_copy') }
function call() { void track('call'); window.location.href = `tel:${value('phone')}` }
function email() { void track('email'); window.location.href = `mailto:${value('email')}` }
function escapeVcard(text: string) { return text.replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/;/g, '\\;').replace(/\n/g, '\\n') }
function saveContact() { const lines = ['BEGIN:VCARD', 'VERSION:3.0', `FN:${escapeVcard(value('display_name'))}`, `ORG:${escapeVcard(value('company_name'))}`]; if (value('headline')) lines.push(`TITLE:${escapeVcard(value('headline'))}`); if (value('phone')) lines.push(`TEL;TYPE=CELL:${value('phone')}`); if (value('email')) lines.push(`EMAIL:${value('email')}`); if (value('website')) lines.push(`URL:${value('website')}`); lines.push('END:VCARD'); const url = URL.createObjectURL(new Blob([lines.join('\r\n')], { type: 'text/vcard;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${value('display_name') || 'contact'}.vcf`; anchor.click(); URL.revokeObjectURL(url); void track('vcard_download') }
function openQr() { showQr.value = true; void track('qr_open') }
async function openProduct(id: string) { const response = await fetch(`${apiBase}/public/products/${id}`); if (response.ok) { selectedProduct.value = await response.json(); void track('product_open', id) } }
function openInquiry(productId: string | null = null) { inquiry.value.product_id = productId; inquiryMessage.value = ''; inquiryError.value = ''; showInquiry.value = true }
async function submitInquiry() { if (!card.value || !inquiry.value.privacy_agreed) { inquiryError.value = '请先阅读并同意隐私授权'; return } submittingInquiry.value = true; inquiryError.value = ''; try { const response = await fetch(`${apiBase}/public/cards/${card.value.card_id}/leads`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...inquiry.value, source }) }); const body = await response.json(); if (!response.ok) { inquiryError.value = body.error?.message ?? '提交失败，请检查填写内容'; return } inquiryMessage.value = body.message; inquiry.value = { name: '', contact: '', demand: '', privacy_agreed: false, product_id: null }; void track('lead_submit') } catch { inquiryError.value = '网络开小差了，请稍后重试' } finally { submittingInquiry.value = false } }
async function loadCard() { if (!cardId) { loading.value = false; return } try { const response = await fetch(`${apiBase}/public/cards/${encodeURIComponent(cardId)}?source=${encodeURIComponent(source)}`); const body = await response.json(); if (!response.ok) { const code = body.error?.code; unavailable.value = code === 'card_offline' ? '这张名片暂时下线了' : code === 'employee_inactive' ? '该员工名片已停止展示' : code === 'company_suspended' ? '该企业名片暂时不可访问' : '没有找到可公开访问的名片'; return } card.value = body; const productResponse = await fetch(`${apiBase}/public/cards/${encodeURIComponent(cardId)}/products`); if (productResponse.ok) products.value = await productResponse.json(); void track('view') } catch { unavailable.value = '网络开小差了，请稍后再试' } finally { loading.value = false } }
async function loadCampaign() { if (!campaignSlug) return; loading.value = true; try { const response = await fetch(`${apiBase}/public/campaigns/${encodeURIComponent(campaignSlug)}`); const body = await response.json(); if (!response.ok) { unavailable.value = body.error?.message ?? '活动不存在或已关闭'; return } marketing.value = body; marketingValues.value = Object.fromEntries(body.fields.map((field: CampaignField) => [field.key, ''])) } catch { unavailable.value = '网络开小差了，请稍后再试' } finally { loading.value = false } }
async function submitCampaign() { if (!marketingConsent.value) { marketingError.value = '请先阅读并同意隐私说明'; return } marketingSubmitting.value = true; marketingError.value = ''; try { const response = await fetch(`${apiBase}/public/campaigns/${encodeURIComponent(campaignSlug)}/submissions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values: marketingValues.value, privacy_agreed: true, source, website: '' }) }); const body = await response.json(); if (!response.ok) { marketingError.value = body.error?.message ?? '报名提交失败'; return } marketingMessage.value = body.message } catch { marketingError.value = '网络开小差了，请稍后再试' } finally { marketingSubmitting.value = false } }
async function askAi() { aiLoading.value = true; aiError.value = ''; try { const response = await fetch(`${apiBase}/public/ai/${encodeURIComponent(aiCompanyCode)}/ask`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: aiQuestion.value, visitor_id: visitorId() }) }); const body = await response.json(); if (!response.ok) { aiError.value = body.error?.message ?? 'AI 助手暂时无法回答'; return } aiAnswer.value = body } catch { aiError.value = '网络开小差了，请稍后再试' } finally { aiLoading.value = false } }
async function feedback(rating: -1 | 1) { if (!aiAnswer.value) return; await fetch(`${apiBase}/public/ai/interactions/${aiAnswer.value.interaction_id}/feedback`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating }) }) }
onMounted(() => campaignSlug ? loadCampaign() : aiCompanyCode ? (loading.value = false) : loadCard())
</script>

<template>
  <main v-if="!cardId && !campaignSlug && !aiCompanyCode" class="landing"><section class="landing-hero"><span class="landing-logo">DC</span><span class="badge">V1.5.0</span><div><p>DIGITAL BUSINESS CARD</p><h1>每一次连接，<br />都能走向下一步。</h1><span>通过专属名片展示企业、产品并承接客户咨询。</span></div></section><section class="landing-info"><p>OPEN READY</p><h2>从企业知识到可靠问答</h2><div><article>企业授权知识</article><article>回答附带来源</article><article>不确定时转人工</article></div></section></main>
  <main v-else-if="campaignSlug && loading" class="state-page"><span class="state-mark">DC</span><h1>正在打开活动</h1></main>
  <main v-else-if="campaignSlug && unavailable" class="state-page"><span class="state-mark">—</span><h1>{{ unavailable }}</h1></main>
  <main v-else-if="campaignSlug && marketing" class="public-card campaign-page"><header class="public-profile"><p>MARKETING CAMPAIGN</p><h1>{{ marketing.name }}</h1><h2 v-if="marketing.description">{{ marketing.description }}</h2><small v-if="marketing.remaining != null">剩余 {{ marketing.remaining }} 个名额</small></header><section v-if="marketing.state !== 'open'" class="content-module"><h3>{{ marketing.state === 'not_started' ? '活动尚未开始' : marketing.state === 'full' ? '活动名额已满' : '活动已经结束' }}</h3></section><form v-else class="content-module form-stack" @submit.prevent="submitCampaign"><label v-for="field in marketing.fields" :key="field.key"><span>{{ field.label }}{{ field.required ? ' *' : '' }}</span><textarea v-if="field.type === 'textarea'" v-model.trim="marketingValues[field.key]" :required="field.required" rows="4" /><select v-else-if="field.type === 'select'" v-model="marketingValues[field.key]" :required="field.required"><option value="">请选择</option><option v-for="option in field.options" :key="option">{{ option }}</option></select><input v-else v-model.trim="marketingValues[field.key]" :type="field.type === 'email' ? 'email' : field.type === 'phone' ? 'tel' : 'text'" :required="field.required" /></label><label class="privacy-consent"><input v-model="marketingConsent" type="checkbox" /><span>{{ marketing.privacy_notice }}</span></label><div v-if="marketingMessage" class="notice success">{{ marketingMessage }}</div><div v-if="marketingError" class="notice error">{{ marketingError }}</div><button class="primary-action" :disabled="marketingSubmitting">{{ marketingSubmitting ? '提交中…' : '立即报名' }}</button></form></main>
  <main v-else-if="aiCompanyCode" class="public-card campaign-page"><header class="public-profile"><p>ENTERPRISE AI</p><h1>企业 AI 助手</h1><h2>回答仅基于企业已授权资料</h2></header><form class="content-module form-stack" @submit.prevent="askAi"><label><span>请输入问题</span><textarea v-model.trim="aiQuestion" rows="4" minlength="2" required /></label><button class="primary-action" :disabled="aiLoading">{{ aiLoading ? '正在查找可靠依据…' : '发送问题' }}</button><div v-if="aiError" class="notice error">{{ aiError }}</div></form><section v-if="aiAnswer" class="content-module"><p class="section-label">AI ANSWER</p><h3>{{ aiAnswer.uncertain ? '暂未找到可靠依据' : '基于企业资料的回答' }}</h3><p>{{ aiAnswer.answer }}</p><small>{{ aiAnswer.suggestion_notice }}</small><div v-if="aiAnswer.citations.length"><h4>来源</h4><article v-for="item in aiAnswer.citations" :key="item.source_id"><b>{{ item.title }}</b><p>{{ item.excerpt }}</p></article></div><div class="actions"><button type="button" @click="feedback(1)">有帮助</button><button type="button" @click="feedback(-1)">需改进</button><a v-if="aiAnswer.handoff_url" :href="aiAnswer.handoff_url">转人工 / 留资</a></div></section></main>
  <main v-else-if="loading" class="state-page"><span class="state-mark">DC</span><h1>正在打开名片</h1><p>请稍候，正在加载公开信息…</p></main>
  <main v-else-if="unavailable" class="state-page"><span class="state-mark">—</span><h1>{{ unavailable }}</h1><p>名片可能尚未发布、已下线，或所属企业暂时停用。</p></main>
  <main v-else-if="card" class="public-card" :style="{ '--theme': value('theme_color') || '#1c6a42' }">
    <header class="public-brand"><img v-if="value('logo_url')" :src="value('logo_url')" alt="企业 Logo" /><b>{{ value('company_name') }}</b><button type="button" aria-label="显示分享二维码" @click="openQr">▦</button></header>
    <template v-for="module in modules" :key="module">
      <section v-if="module === 'profile'" class="public-profile"><img v-if="value('avatar_url')" :src="value('avatar_url')" alt="头像" /><span v-else>{{ value('display_name').slice(0, 1) }}</span><p>HELLO, I AM</p><h1>{{ value('display_name') }}</h1><h2 v-if="value('headline')">{{ value('headline') }}</h2></section>
      <section v-else-if="module === 'contact'" class="action-grid"><button v-if="value('phone')" type="button" @click="call"><i>☎</i><span>拨打电话</span></button><button v-if="value('email')" type="button" @click="email"><i>✉</i><span>发送邮件</span></button><button v-if="value('wechat')" type="button" @click="copyWechat"><i>微</i><span>复制微信</span></button><button type="button" @click="saveContact"><i>＋</i><span>保存通讯录</span></button></section>
      <section v-else-if="module === 'bio' && value('bio')" class="content-module"><p class="section-label">ABOUT</p><h3>关于我</h3><p>{{ value('bio') }}</p></section>
      <section v-else-if="module === 'social' && socials.length" class="content-module"><p class="section-label">SOCIAL</p><h3>社交账号</h3><a v-for="social in socials" :key="social.url" :href="social.url" target="_blank" rel="noopener noreferrer">{{ social.platform }}<span>↗</span></a></section>
    </template>
    <section v-if="products.length" class="product-module"><p class="section-label">FEATURED PRODUCTS</p><h3>推荐产品</h3><button v-for="product in products" :key="product.id" type="button" class="product-card" @click="openProduct(product.id)"><img v-if="product.cover_url" :src="assetUrl(product.cover_url)" alt="" /><span><b>{{ product.name }}</b><small>{{ product.summary || '查看产品详情' }}</small></span><i>›</i></button></section>
    <section class="inquiry-entry"><p class="section-label">CONTACT US</p><h3>想进一步了解？</h3><p>留下联系方式，名片负责人会尽快与你联系。</p><button type="button" @click="openInquiry()">提交咨询</button></section>
    <section class="share-panel"><p class="section-label">SHARE</p><h3>把这张名片分享给更多人</h3><div><button type="button" @click="copyShare">复制链接</button><button type="button" @click="nativeShare">系统分享</button><button type="button" @click="openQr">二维码</button></div></section>
    <footer>DigitalCard · 安全展示已发布信息</footer>
    <div v-if="showQr" class="qr-backdrop" @click.self="showQr = false"><section class="qr-dialog"><button type="button" aria-label="关闭二维码" @click="showQr = false">×</button><p class="section-label">SCAN TO CONNECT</p><h3>扫码打开名片</h3><img :src="`${apiBase}/public/cards/${card.card_id}/qr.svg?source=qr`" alt="名片分享二维码" /><small>二维码包含当前名片地址和来源参数</small></section></div>
    <div v-if="selectedProduct" class="product-backdrop" @click.self="selectedProduct = null"><article class="product-detail"><button class="product-close" type="button" @click="selectedProduct = null">×</button><img v-if="selectedProduct.cover_url" class="product-cover" :src="assetUrl(selectedProduct.cover_url)" alt="" /><p class="section-label">PRODUCT</p><h2>{{ selectedProduct.name }}</h2><p>{{ selectedProduct.description || selectedProduct.summary }}</p><div v-if="selectedProduct.gallery_urls.length" class="product-gallery"><img v-for="url in selectedProduct.gallery_urls" :key="url" :src="assetUrl(url)" alt="产品图片" /></div><video v-if="selectedProduct.video_url" controls :src="assetUrl(selectedProduct.video_url)" /><dl v-if="Object.keys(selectedProduct.specifications).length"><template v-for="(item, key) in selectedProduct.specifications" :key="key"><dt>{{ key }}</dt><dd>{{ item }}</dd></template></dl><a v-for="(url, index) in selectedProduct.attachment_urls" :key="url" :href="assetUrl(url)" target="_blank" rel="noopener">查看附件 {{ index + 1 }}</a><button class="product-inquiry" type="button" @click="openInquiry(selectedProduct.id); selectedProduct = null">咨询这个产品</button></article></div>
    <div v-if="showInquiry" class="product-backdrop" @click.self="showInquiry = false"><form class="inquiry-dialog" @submit.prevent="submitInquiry"><button class="product-close" type="button" @click="showInquiry = false">×</button><p class="section-label">INQUIRY</p><h2>提交咨询</h2><label><span>姓名</span><input v-model.trim="inquiry.name" required maxlength="100" /></label><label><span>手机或邮箱</span><input v-model.trim="inquiry.contact" required maxlength="320" /></label><label><span>需求说明</span><textarea v-model.trim="inquiry.demand" rows="4" maxlength="3000" /></label><label class="privacy-check"><input v-model="inquiry.privacy_agreed" type="checkbox" />我同意将以上信息用于本次咨询联系，不用于无关用途。</label><p v-if="inquiryError" class="inquiry-error">{{ inquiryError }}</p><p v-if="inquiryMessage" class="inquiry-success">{{ inquiryMessage }}</p><button class="inquiry-submit" :disabled="submittingInquiry || Boolean(inquiryMessage)">{{ submittingInquiry ? '正在提交…' : '提交咨询' }}</button></form></div>
    <div v-if="toast" class="toast">{{ toast }}</div>
  </main>
</template>
